[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"
combine_as_imports = true

[tool.pytest.ini_options]
filterwarnings = [
    "error",
    "ignore::term_image.exceptions.TermImageWarning:term_image.utils",
]
