[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.mypy]
strict = true

# These modules will go through massive changes real soon
[[tool.mypy.overrides]]
module = [
    'term_image.image.*',
    'term_image.widget.*',
]
ignore_errors = true

[tool.isort]
profile = "black"
combine_as_imports = true

[tool.pytest.ini_options]
filterwarnings = [
    "error",
    "ignore:.+in a terminal:UserWarning:term_image.utils",
    "ignore:.*'urwid.wimp'.*:DeprecationWarning:urwid",
]
